# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a8549ac33f72a7f5ba2ae291322f042f268ee4e88c1d03cf0346c61ba481feced0b7e0afd49a250665000518f3fb8fbbb83fcdccb928212b986d138a1871fee

test:
  secret_key_base: 9f6c086d75bddcae217732b00d599550b39ed4b02379507e3a7ef4443516f51cbd278bcb04b82b612b9f8cbe8b9a2b8bfb4cacd693d2e143a6b19aae1109cf2f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
